### ISSUE TITLE
Update Plugin for Plugin Manager 2.0

### ISSUE THREAD

**Issue by plafosse** [icecr4ck/bnGBA#1]
With the introduction of the Binary Ninja Plugin Manager 2.0 we will be releasing a installation UI for all plugins in the community repository. Please check https://binary.ninja/2019/07/04/plugin-manager-2.0.html for the latest information about how to submit your plugin. If you no longer want your plugin in the repository please disregard this issue

**Comment by psifertex** [comment]
*ping* Any update on this @icecr4ck? Would love to have this installable via the UI and unfortunately we can't create releases via a PR though if you need help updating the plugin.json I'm happy to help with that portion via  PR.

**Comment by icecr4ck** [comment]
Hi @psifertex, I had totally forgotten about it, I will update my plugin as soon as I can.

**Comment by psifertex** [comment]
No worries, figured a reminder couldn't hurt. 

Thanks!

**Comment by icecr4ck** [comment]
Submitted here https://github.com/Vector35/community-plugins/issues/74
