### ISSUE TITLE
The plugin will show a signature error with PE binaries

### ISSUE THREAD

**Issue by fuomag9** [icecr4ck/bnGBA#2]
As per title, if the plugin is enabled it will error out when a PE binary is loaded.
![image](https://user-images.githubusercontent.com/1580624/99273904-e70b9c00-2829-11eb-8d29-4f24fedde73e.png)

**Comment by psifertex** [comment]
Just delete this line: https://github.com/icecr4ck/bnGB/blob/master/gbview.py#L34

**Comment by icecr4ck** [comment]
It's fixed in the release 1.0.1. Thank you!
